version: '3'

vars:
  APP_NAME: "echo"
  BIN_DIR: "bin"
  PACKAGE_MANAGER: '{{.PACKAGE_MANAGER | default "npm"}}'
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml

tasks:
  build:
    summary: Builds the Windows desktop application
    cmds:
      - task: windows:build

  package:
    summary: Packages the Windows desktop application
    cmds:
      - task: windows:package

  run:
    summary: Runs the Windows desktop application
    cmds:
      - task: windows:run

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
