// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function Load(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(3648886958);
}

export function ResetAvatar(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(8405616);
}

export function Save(settings: config$0.Settings): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(2796213707, settings);
}
