// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the complete local preference contract persisted by the desktop shell.
 */
export interface Settings {
    "anonymous_id": string;
    "nickname": string;
    "avatar_id": string;
    "push_to_talk_key": string;
    "microphone_device": string;
    "output_device": string;
    "voice_mode": string;
    "output_volume": number;
}
